<?php
$urlErp='http://192.168.1.200:28880/adxwsvc/services/CAdxWebServiceXmlCC?wsdl';
$codeLang='ITA';
$codeUser='ws01';
$password='8LcM8';
$poolAlias='WSPROD';
$requestConfig='adxwss.trace.on=on&adxwss.trace.size=16384&adonix.trace.on=on&adonix.trace.level=3&adonix.trace.size=8';
$metodo_ricerca_telaio="YCHKTEL";
$metodo_lista_workpool="YLISTWRK";
$metodo_verifica_telaio="YGETID";
$metodo_inserisci_workpool="YCREWRKPL";
$metodo_lista_reparti="YLISTPRG";
$metodo_cancella_workpool="YDELWRK";
?>
